"""Page for skipping manual configuration and importing a pre-configured model (.xlsx file).

Effectively, we reuse logic from the simulation step of the model, but add an Import button and a
file upload component.  The imported file should have the same format as the one generated by
the export.py module, used by the main dashboard.
"""

import typing
from collections.abc import Generator

import dash
import dash_mantine_components as dmc
from dash import dcc
from dash.development.base_component import Component as DashComponent
from dash_compose import composition
from plotly import graph_objects as go

from virus_sim_dashboard.config import config
from virus_sim_dashboard.util import DEFAULT_FIGURE_LAYOUT

dash.register_page(__name__, path="/import")


@composition
def layout() -> Generator[DashComponent, None, DashComponent]:
    """Main content area layout."""
    with dmc.AppShellMain(
        None, w=config.app_width, px=0, m="md", pt=config.header_height, pb=config.footer_height
    ) as ret:
        with dmc.Stack(None, gap="xl", m=0, p=0):
            with dmc.Stack(None, gap="sm", m=0, p=0):
                yield dmc.Title("Import and run pre-configured model", order=2)
                yield dmc.Text(
                    "This page allows you to import a pre-configured model from an .xlsx file "
                    "and run the simulation without going through the manual configuration steps."
                )
            with dmc.Group(None, gap="md", m=0, p=0):
                yield dcc.Upload(
                    id="import-file-input",
                    accept=".xlsx",
                )
                yield dmc.Button("Import and run simulation", id="import-button", size="xl")
            with dmc.Stack(None, gap="md", m=0, p=0):
                yield dmc.Title("Simulation Progress", order=3)
                with dmc.Group(None, gap="md", m=0, p=0):
                    yield dmc.Text("Waiting for file...", id="import-mode-progress-text")
                    yield dmc.Progress(
                        color="blue",
                        size="xl",
                        w=900,
                        # For non-numeric progress, set value to 100 and use the animated property
                        # to show an indeterminate progress bar
                        value=100,
                        animated=True,
                        id="import-mode-progress",
                    )
            yield dcc.Store(id="store-import-mode-sim-results")  # Store for simulation results

            with dmc.Stack(
                None,
                id="stack-import-mode-sim-results",
                gap="md",
                # style={"display": "none"},  # hide until we have results to show
            ):
                yield dmc.Title("Simulation Results", order=3)
                yield dmc.MultiSelect(
                    # Since we don't know the age groups in advance, default to 0+
                    size="md",
                    data=[{"label": "0+", "value": "0+"}],
                    value=["0+"],
                    label="Filter by Age Groups",
                    id="multiselect-import-mode-sim-output-groupings",
                    placeholder="Click here to select age groups",
                )
                yield dmc.Button(
                    "Select All",
                    id="btn-import-mode-output-groupings-all",
                )
                yield dmc.Title("GIM Beds Occupancy (selected age groups)", order=4)

                layout_gim: dict[str, typing.Any] = DEFAULT_FIGURE_LAYOUT.copy()
                layout_gim["title"]["text"] = "GIM Beds Occupancy (daily maximum)"
                figure_gim = go.Figure(layout=layout_gim)
                yield dcc.Graph(
                    id={"type": "graph", "index": "import-mode-gim-beds-occupancy"},
                    figure=figure_gim,
                )

                yield dmc.Title("ICU Beds Occupancy (selected age groups)", order=4)

                layout_icu: dict[str, typing.Any] = DEFAULT_FIGURE_LAYOUT.copy()
                layout_icu["title"]["text"] = "ICU Beds Occupancy (daily maximum)"
                figure_icu = go.Figure(layout=layout_icu)
                yield dcc.Graph(
                    id={"type": "graph", "index": "import-mode-icu-beds-occupancy"},
                    figure=figure_icu,
                )

                with dmc.Group(None, gap="md"):
                    yield dmc.Button(
                        "Download simulation results (.xlsx)",
                        disabled=True,
                        id="btn-import-mode-download-sim-results",
                    )
                    yield dcc.Download(id="download-import-mode-sim-results")
    return ret
